### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create
POST localhost:8080/category/create
Content-Type: application/json

{
  "nameUz": "Toshkent",
  "nameRu": "Тошкент",
  "nameEn": "Tashkent",
  "regionKey": "TASH"
}